#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Ready to commit changes!'
dotnet husky run --name dotnet-format-staged-files

echo 'Build'
dotnet build --no-restore 

echo 'Test'
dotnet test --no-restore

echo 'Completed pre-commit checks' 
